import type {Metadata} from "next"
import Link from "next/link"

async function getData() {
	const res = await fetch('https://jsonplaceholder.typicode.com/posts', {
		next: {
			revalidate: 60
		}
	})

	if (!res.ok) throw new Error(`Error text ${res.statusText}`)

	return res.json()
}

export const metadata: Metadata = {
	title: "blog page App",
	description: "Generated by create next app",
}

export default async function About() {
	const postData = await getData()
	return (
		<div className='blog'>
			<h1 >Blog Page</h1 >
			<ul >
				{postData.map((item: any, index: number) =>
					<li key={item.id}>
						<span>{index + 1}.</span>
						<Link href={`/blog/${item.id}`} target={'_blank'}>{item.title}</Link >
					</li >
				)}
			</ul >
		</div>
	)
}