import type {Metadata} from "next";

export const metadata: Metadata = {
	title: "About page App",
	description: "Generated by create next app",
};
export default function About() {
	return	<h1>Select subitem</h1>
}