import type {Metadata} from "next";

export const metadata: Metadata = {
	title: "About Contacts page App",
	description: "Generated by create next app",
};
export default function Contacts() {
	return	<h1>About page Contacts</h1>
}