import type {Metadata} from "next";

export const metadata: Metadata = {
	title: "About Team page App",
	description: "Generated by create next app",
};
export default function Team() {
	return	<h1>About page Team</h1>
}